version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/instance/admin.db
